site_name: Fairino Integration Manual

theme:
  name: material

  logo: https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg

  palette:
    # Light mode (default)
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.sidebar
    - navigation.collapse
    - search.highlight
    - content.code.copy
    - content.tabs.link

nav:
  - PLC Integration:
      - Mitsubishi FX: plc/mitsubishi-fx.md
      - Mitsubishi R: plc/mitsubishi-r.md
      - Mitsubishi Q: plc/mitsubishi-q.md
      - Omron NX: plc/omron-nx.md
      - Omron NJ: plc/omron-nj.md

  - HMI Integration:
      - Mitsubishi GOT: hmi/mitsubishi-got.md
      - Innovance: hmi/innovance.md

  - Camera Integration:
      - Webcam: camera/webcam.md
      - Cognex: camera/cognex.md
      - Keyence: camera/keyence.md

  - Downloads: downloads.md
